apiVersion: v1
kind: Service
metadata:
  name: pod-network-server
  namespace: pod-network-lab

spec:
  type: ClusterIP

  selector:
    app: pod-network-server

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80