apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-config-reader-binding
  namespace: devops-learning

subjects:
- kind: ServiceAccount
  name: catalog-sa
  namespace: devops-learning

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalog-config-reader