apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit-test
  namespace: devops-learning
spec:
  containers:
    - name: cpu-burner
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          while true; do
            echo "CPU workload running"
          done
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "500m"
          memory: "64Mi"