apiVersion: v1
kind: Pod

metadata:
  name: noexecute-toleration-test
  namespace: devops-learning

spec:
  tolerations:
    - key: dedicated
      operator: Equal
      value: execute-demo
      effect: NoExecute
      tolerationSeconds: 30

  containers:
    - name: test
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "NoExecute tolerationSeconds test"
          sleep 3600