apiVersion: v1
kind: Pod

metadata:
  name: prefer-no-schedule-test
  namespace: devops-learning

spec:
  containers:
    - name: test
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "PreferNoSchedule test"
          sleep 3600