apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  namespace: devops-learning
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"