apiVersion: v1
kind: Pod
metadata:
  name: resource-memory-test
  namespace: devops-learning
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"