apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: devops-learning
data:
  APP_MODE: "catalog"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: devops-learning
data:
  APP_MODE: "payment"