apiVersion: v1
kind: Pod

metadata:
  name: scheduler-preferred-test
  namespace: devops-learning

spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: scheduler-demo
                operator: In
                values:
                  - "true"

  containers:
    - name: test
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Preferred node affinity test"
          sleep 3600