apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-nginx-config
  namespace: pod-network-lab
data:
  default.conf: |
    server {
      listen 80;

      location / {
        default_type text/plain;
        return 200 "CATALOG SERVICE\n";
      }
    }